astra_db:
  collection_name: "e_commerce_chatbot"

embedding_model:
  provider: "ollama"
  model_name: "nomic-embed-text:v1.5"

retriever:
  top_k: 4

llm:
  provider: "groq"
  model_name: "gemini-embedding-exp-03-07" 